### ISSUE TITLE
Bulgaria map is not correctly displayed in Country Map chart

### ISSUE THREAD

**Issue by dvracheva** [apache-superset/superset-ui#569]
Hi,
I've tryed to create Country Map chart to locate some objects in Bulgaria and I've run across the following issues:
The codes of region/province/department, required by the the input when creating country map, are not in compliance with ISO-3166-2 in packages/superset-ui-legacy-plugin-chart-country-map/src/countries/bulgaria.geojson. Ok, then I changed the codes in my source DB table to be in the format like in the mentioned .geojson file and the Bulgaria map was displayed. Unfortunately - it is not correctly displayed - it is displayed like a small point in the upper corner of some rectangle.
I have looked at the DEMO  for superset-ui in Github - the issue thing there. When you select Bulgaria from the dropdown, only a point inside a rectangle is shown.
You can check it here:
https://apache-superset.github.io/superset-ui/?path=/story/legacy-chart-plugins-legacy-plugin-chart-country-map--basic

**Comment by zeridon** [comment]
NOTE: the problem lies with superset-ui-legacy-plugin-chart-country-map/src/countries.js 

@djok according to ba113c2056958ec0c0a84dafff74952377a45c53 you have added the bulgaria geojson map, can you comment?

@pkdotson according to 35e78ad895721e1e9807a4451bca1dc448e96e36 you have implemented controlPanel.ts could you also comment?

**Comment by djok** [comment]
The problem is in 'file-loader!./countries/bulgaria.geojson', will prepare new geojson file

**Comment by ktmud** [comment]
Related: https://github.com/apache/superset/issues/12987
